# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_runtime_pb2 as agent__runtime__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRuntimeStub:
    """─────────────────────────────────────────────────────────────────────────────
    AgentRuntime — served INSIDE the sandbox container on 0.0.0.0:50051 (TCP);
    the host reaches it via a published host port or by container name on a
    shared Docker network. The host's `POST /agents/{id}` endpoint drives exactly
    one turn per RunTurn call and cancels an in-flight turn with Interrupt. The
    container has no host secrets and runs behind the host's AllowlistEgressProxy
    — anything needing egress or credentials goes back out through HostBridge
    (below), which is the single monitoring choke point.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTurn = channel.unary_stream(
                '/krutrim_agent.runtime.v1.AgentRuntime/RunTurn',
                request_serializer=agent__runtime__pb2.RunTurnRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.RunEvent.FromString,
                _registered_method=True)
        self.Interrupt = channel.unary_unary(
                '/krutrim_agent.runtime.v1.AgentRuntime/Interrupt',
                request_serializer=agent__runtime__pb2.InterruptRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.InterruptAck.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/krutrim_agent.runtime.v1.AgentRuntime/Health',
                request_serializer=agent__runtime__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/krutrim_agent.runtime.v1.AgentRuntime/Shutdown',
                request_serializer=agent__runtime__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.ShutdownAck.FromString,
                _registered_method=True)


class AgentRuntimeServicer:
    """─────────────────────────────────────────────────────────────────────────────
    AgentRuntime — served INSIDE the sandbox container on 0.0.0.0:50051 (TCP);
    the host reaches it via a published host port or by container name on a
    shared Docker network. The host's `POST /agents/{id}` endpoint drives exactly
    one turn per RunTurn call and cancels an in-flight turn with Interrupt. The
    container has no host secrets and runs behind the host's AllowlistEgressProxy
    — anything needing egress or credentials goes back out through HostBridge
    (below), which is the single monitoring choke point.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def RunTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interrupt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTurn': grpc.unary_stream_rpc_method_handler(
                    servicer.RunTurn,
                    request_deserializer=agent__runtime__pb2.RunTurnRequest.FromString,
                    response_serializer=agent__runtime__pb2.RunEvent.SerializeToString,
            ),
            'Interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.Interrupt,
                    request_deserializer=agent__runtime__pb2.InterruptRequest.FromString,
                    response_serializer=agent__runtime__pb2.InterruptAck.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agent__runtime__pb2.HealthRequest.FromString,
                    response_serializer=agent__runtime__pb2.HealthReply.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=agent__runtime__pb2.ShutdownRequest.FromString,
                    response_serializer=agent__runtime__pb2.ShutdownAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'krutrim_agent.runtime.v1.AgentRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('krutrim_agent.runtime.v1.AgentRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntime:
    """─────────────────────────────────────────────────────────────────────────────
    AgentRuntime — served INSIDE the sandbox container on 0.0.0.0:50051 (TCP);
    the host reaches it via a published host port or by container name on a
    shared Docker network. The host's `POST /agents/{id}` endpoint drives exactly
    one turn per RunTurn call and cancels an in-flight turn with Interrupt. The
    container has no host secrets and runs behind the host's AllowlistEgressProxy
    — anything needing egress or credentials goes back out through HostBridge
    (below), which is the single monitoring choke point.
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def RunTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/krutrim_agent.runtime.v1.AgentRuntime/RunTurn',
            agent__runtime__pb2.RunTurnRequest.SerializeToString,
            agent__runtime__pb2.RunEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/krutrim_agent.runtime.v1.AgentRuntime/Interrupt',
            agent__runtime__pb2.InterruptRequest.SerializeToString,
            agent__runtime__pb2.InterruptAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/krutrim_agent.runtime.v1.AgentRuntime/Health',
            agent__runtime__pb2.HealthRequest.SerializeToString,
            agent__runtime__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/krutrim_agent.runtime.v1.AgentRuntime/Shutdown',
            agent__runtime__pb2.ShutdownRequest.SerializeToString,
            agent__runtime__pb2.ShutdownAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HostBridgeStub:
    """─────────────────────────────────────────────────────────────────────────────
    HostBridge — served on the HOST for the life of one RunTurn on a TCP port
    (<bind_host>:<port>) the container dials back via <callback_host>. The
    in-sandbox agent calls back out through this for every LLM completion and
    every host-side tool (web_search / fetch_url / rag). The host performs the
    real request, LOGS it (model params, token usage, tool args/results), and
    streams the result back — so the container never holds credentials and the
    host remains the sole audit trail for LLM/tool egress.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatComplete = channel.unary_stream(
                '/krutrim_agent.runtime.v1.HostBridge/ChatComplete',
                request_serializer=agent__runtime__pb2.ChatRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.InvokeHostTool = channel.unary_unary(
                '/krutrim_agent.runtime.v1.HostBridge/InvokeHostTool',
                request_serializer=agent__runtime__pb2.HostToolRequest.SerializeToString,
                response_deserializer=agent__runtime__pb2.HostToolReply.FromString,
                _registered_method=True)


class HostBridgeServicer:
    """─────────────────────────────────────────────────────────────────────────────
    HostBridge — served on the HOST for the life of one RunTurn on a TCP port
    (<bind_host>:<port>) the container dials back via <callback_host>. The
    in-sandbox agent calls back out through this for every LLM completion and
    every host-side tool (web_search / fetch_url / rag). The host performs the
    real request, LOGS it (model params, token usage, tool args/results), and
    streams the result back — so the container never holds credentials and the
    host remains the sole audit trail for LLM/tool egress.
    ─────────────────────────────────────────────────────────────────────────────
    """

    def ChatComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeHostTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatComplete': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatComplete,
                    request_deserializer=agent__runtime__pb2.ChatRequest.FromString,
                    response_serializer=agent__runtime__pb2.ChatChunk.SerializeToString,
            ),
            'InvokeHostTool': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeHostTool,
                    request_deserializer=agent__runtime__pb2.HostToolRequest.FromString,
                    response_serializer=agent__runtime__pb2.HostToolReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'krutrim_agent.runtime.v1.HostBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('krutrim_agent.runtime.v1.HostBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostBridge:
    """─────────────────────────────────────────────────────────────────────────────
    HostBridge — served on the HOST for the life of one RunTurn on a TCP port
    (<bind_host>:<port>) the container dials back via <callback_host>. The
    in-sandbox agent calls back out through this for every LLM completion and
    every host-side tool (web_search / fetch_url / rag). The host performs the
    real request, LOGS it (model params, token usage, tool args/results), and
    streams the result back — so the container never holds credentials and the
    host remains the sole audit trail for LLM/tool egress.
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def ChatComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/krutrim_agent.runtime.v1.HostBridge/ChatComplete',
            agent__runtime__pb2.ChatRequest.SerializeToString,
            agent__runtime__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeHostTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/krutrim_agent.runtime.v1.HostBridge/InvokeHostTool',
            agent__runtime__pb2.HostToolRequest.SerializeToString,
            agent__runtime__pb2.HostToolReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
